import streamlit as st
import joblib
import numpy as np


# -----------------------------
# Load trained model
# -----------------------------
model = joblib.load("models/breast_cancer_model.pkl")


# -----------------------------
# Page configuration
# -----------------------------
st.set_page_config(
    page_title="Breast Cancer Detection",
    page_icon="🩺",
    layout="wide"
)


# -----------------------------
# Header
# -----------------------------
st.title("🩺 Breast Cancer Detection")

st.write(
    "Enter the diagnostic measurements below to get a prediction "
    "from the trained machine learning model."
)

st.warning(
    "⚠️ This application is for educational and demonstration purposes only. "
    "It is not a medical diagnosis."
)


# -----------------------------
# Feature names
# -----------------------------
mean_features = [
    "Mean Radius",
    "Mean Texture",
    "Mean Perimeter",
    "Mean Area",
    "Mean Smoothness",
    "Mean Compactness",
    "Mean Concavity",
    "Mean Concave Points",
    "Mean Symmetry",
    "Mean Fractal Dimension"
]

error_features = [
    "Radius Error",
    "Texture Error",
    "Perimeter Error",
    "Area Error",
    "Smoothness Error",
    "Compactness Error",
    "Concavity Error",
    "Concave Points Error",
    "Symmetry Error",
    "Fractal Dimension Error"
]

worst_features = [
    "Worst Radius",
    "Worst Texture",
    "Worst Perimeter",
    "Worst Area",
    "Worst Smoothness",
    "Worst Compactness",
    "Worst Concavity",
    "Worst Concave Points",
    "Worst Symmetry",
    "Worst Fractal Dimension"
]


feature_names = mean_features + error_features + worst_features


# -----------------------------
# Example values
# -----------------------------
default_values = [
    14.0,
    19.0,
    92.0,
    654.0,
    0.096,
    0.104,
    0.089,
    0.048,
    0.181,
    0.063,
    0.405,
    1.216,
    2.866,
    40.0,
    0.007,
    0.025,
    0.031,
    0.012,
    0.021,
    0.004,
    16.0,
    25.0,
    107.0,
    880.0,
    0.132,
    0.254,
    0.272,
    0.115,
    0.290,
    0.083
]


# -----------------------------
# Input helper
# -----------------------------
def create_inputs(features, defaults):
    values = []

    for i in range(0, len(features), 2):
        col1, col2 = st.columns(2)

        with col1:
            value1 = st.number_input(
                features[i],
                min_value=0.0,
                value=float(defaults[i]),
                format="%.6f",
                key=features[i]
            )
            values.append(value1)

        if i + 1 < len(features):
            with col2:
                value2 = st.number_input(
                    features[i + 1],
                    min_value=0.0,
                    value=float(defaults[i + 1]),
                    format="%.6f",
                    key=features[i + 1]
                )
                values.append(value2)

    return values
# -----------------------------
# Mean Features
# -----------------------------
st.header("📊 Mean Features")

st.caption(
    "Average measurements of the cell nuclei."
)

mean_values = create_inputs(
    mean_features,
    default_values[:10]
)


# -----------------------------
# Error Features
# -----------------------------
st.header("📐 Error Features")

st.caption(
    "Standard error measurements of the diagnostic features."
)

error_values = create_inputs(
    error_features,
    default_values[10:20]
)


# -----------------------------
# Worst Features
# -----------------------------
st.header("🔬 Worst Features")

st.caption(
    "Largest or most significant measurements recorded for the cell nuclei."
)

worst_values = create_inputs(
    worst_features,
    default_values[20:30]
)


# -----------------------------
# Combine all inputs
# -----------------------------
inputs = mean_values + error_values + worst_values


# -----------------------------
# Prediction button
# -----------------------------
st.divider()

if st.button(
    "🔍 Predict",
    use_container_width=True
):

    input_data = np.array(inputs).reshape(1, -1)

    prediction = model.predict(input_data)[0]

    st.header("Prediction Result")

    if prediction == 0:

        st.error(
            "🔴 Prediction: Malignant"
        )

    else:

        st.success(
            "🟢 Prediction: Benign"
        )

    st.info(
        "The prediction is generated by the trained machine learning model "
        "using the 30 diagnostic features entered above."
    )